# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shattered Journal Games
email: contact@shatteredjournalgames.com
description: >- # this means to ignore newlines until "baseurl:"
  Shattered Journal Games is a collective of dedicated game devs who create small scope high quality products.
  We focus on making engaging multiplayer experiences and arcade style mobile games.
baseurl: ""
url: "https://shatteredjournalgames.com"

# Includes an icon in the footer for each link you enter
footer-links:
  twitter: https://www.twitter.com/ShatteredJGames
  bluesky: https://bsky.app/profile/shatteredjgames.bsky.social
  instagram: https://www.instagram.com/shatteredjgames/
  facebook: https://www.facebook.com/people/Shattered-Journal-Games/61552987569806/
  tiktok: https://www.tiktok.com/@shatteredjournalgames
  youtube: https://www.youtube.com/channel/UCLt7nQEMz0sDMYZDFerUMkg
  steam: https://store.steampowered.com/publisher/ShatteredJournalGames
  itch: https://ShatteredJournalGames.itch.io
  newgrounds: https://ShatteredJournal.newgrounds.com
  discord: https://discord.com/invite/7m8vJRV/

collections:
  games:
    output: true
  franchises:
    output: true
  team:
    output: true

# Build settings
markdown: kramdown

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji
  - jekyll-remote-include

plugins:
- jekyll-feed
- jemoji
- jekyll-remote-include

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
