# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jason Gertner
email: contact@shatteredjournalgames.com
description: >- # this means to ignore newlines until "baseurl:"
  I’m a game developer, and I want to create more and more games.
  I’ve been super passionate about making games since I was eight years old; making fun experiences that other people can enjoy is what I want to always do.
  I like to experiment with new and unique mechanics, especially when doing game jams.
  My specialties include designing and programming multiplayer games, enemies and bosses, and making games that are small scope and fun.
baseurl: ""
url: "https://jasongertner.com"

# Includes an icon in the footer for each link you enter
footer-links:
  twitter: https://www.twitter.com/jasoonmargoon
  bluesky: https://bsky.app/profile/jasoonmargoon.bsky.social
  instagram: https://www.instagram.com/jasoonmargoon/
  itch: https://jasoonmargoon.itch.io/
  newgrounds: https://jasoonmargoon.newgrounds.com
  linkedin: https://www.linkedin.com/in/jasongertner/

collections:
  games:
    output: true
  franchises:
    output: true
  team:
    output: true

# Build settings
markdown: kramdown

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji
  - jekyll-remote-include

plugins:
- jekyll-feed
- jemoji
- jekyll-remote-include

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
